### ISSUE TITLE
Token on the diagonal grid square to the attacker gets cover from other tokens

### ISSUE THREAD

**Issue by TrofimSelbs** [caewok/fvtt-token-cover#17] opened 2024-02-05 12:06 UTC
Hey, there is an issue with this scenario. I use DMG preset. This happened with all but this module disabled as well, so I don't believe it is some weird interaction between this module and some other one.

On the photo below you can see that the diagonally standing token is in half cover, when it shouldn't be
![SCR-20240205-kvxu](https://github.com/caewok/fvtt-token-cover/assets/124184162/9b2181f3-42a7-4ed1-b94b-5beac27d94a6)

**Comment by caewok** [comment] 2024-02-08 00:15
I am still pondering whether this is fixable. But in the meantime, if you change the Low Cover Trigger to 0.55, the diagonal target would not have cover.

The issue is both for tokens and walls. Token boundaries actually overlap one another when they are adjacent in Foundry. So from the top right corner of the hero's token, drawing a line vertically or horizontally runs into the top left and bottom right tokens, respectively. I will see if I can slightly shrink token boundaries to compensate. 

Walls have a similar [overlap issue](https://github.com/caewok/fvtt-token-visibility/issues/77). This is more complicated, because I cannot shrink the walls and I have to be able to distinguish between a non-blocking situation and a situation where a token is adjacent to a wall and thus should not be seen from the other side of the wall.

**Comment by TrofimSelbs** [comment] 2024-02-08 17:04
thank you for looking into this one! 🙏
I see that it is more complicated then I thought

**Comment by caewok** [comment] 2024-02-11 18:52
Addressed in v0.6.5. Walls will still have [overlap issues](https://github.com/caewok/fvtt-token-visibility/issues/77) but I will look into that further.

**Closed by caewok** 2024-02-11 18:52 UTC

**Comment by TrofimSelbs** [comment] 2024-02-11 19:02
thanks a lot!
