### ISSUE TITLE
Cover fails to be applied in PF2e

### ISSUE THREAD

**Issue by Crusufix** [caewok/fvtt-token-cover#41] opened 2024-11-07 02:34 UTC
The Cover affect doesn't appear on target in PF2e

System: PF2e 6.6.1
Foundry: 12.331
ATC version: 0.97
Clean world with only ATC, Socketlib, and LibWrapper enabled

I'm getting this console error:
Foundry VTT | Error thrown in hooked function 'targetToken' for hook 'targetToken'
#call @ foundry.js:635
callAll @ foundry.js:589
#hook @ foundry.js:31843
add @ foundry.js:31818
setTarget @ foundry.js:60980
_onTarget @ foundry.js:1838
_executeKeybind @ foundry.js:2462
_processKeyboardContext @ foundry.js:2503
_handleKeyboardEvent @ foundry.js:2561
(anonymous) @ foundry.js:2175Understand this warningAI
foundry.js:655 Error: Error thrown in hooked function 'targetToken' for hook 'targetToken'. Cannot assign to read only property '_id' of object '#<EffectPF2e>'
[Detected 1 package: tokencover(0.9.7)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at #hook (foundry.js:31843:11)
    at UserTargets.add (foundry.js:31818:15)
    at TokenPF2e.setTarget (foundry.js:60980:20)
    at Object._onTarget [as onDown] (foundry.js:1838:13)
    at KeyboardManager._executeKeybind (foundry.js:2462:66)
    at KeyboardManager._processKeyboardContext (foundry.js:2503:33)
    at KeyboardManager._handleKeyboardEvent (foundry.js:2561:10)
    at foundry.js:2175:54Caused by: TypeError: Cannot assign to read only property '_id' of object '#<EffectPF2e>'
[Detected 1 package: tokencover(0.9.7)]
    at CoverPF2E._addToTokenLocally (UniqueItemEffect.js:75:27)
    at CoverPF2E.addToTokenLocally (AbstractUniqueEffect.js:377:16)
    at TokenCover._replaceCover (TokenCover.js:443:49)
    at TokenCover.updateCover (TokenCover.js:406:22)
    at TokenCover.targetStatusChanged (TokenCover.js:382:40)
    at Object.targetToken [as fn] (Token.js:286:21)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at #hook (foundry.js:31843:11)
    at UserTargets.add (foundry.js:31818:15)
    at TokenPF2e.setTarget (foundry.js:60980:20)
    at Object._onTarget [as onDown] (foundry.js:1838:13)
    at KeyboardManager._executeKeybind (foundry.js:2462:66)
    at KeyboardManager._processKeyboardContext (foundry.js:2503:33)
    at KeyboardManager._handleKeyboardEvent (foundry.js:2561:10)
    at foundry.js:2175:54

![image](https://github.com/user-attachments/assets/b7610a07-ddad-4ec3-ac1f-5ee1543c1e96)

**Comment by Khaldrys** [comment] 2024-11-12 17:27
Hi guys, same issue here, 

System: PF2e 6.6.2
Foundry: 12.331
ATC version: 0.97

Error: Error thrown in hooked function 'targetToken' for hook 'targetToken'. Cannot assign to read only property '_id' of object '#<EffectPF2e>'
[Detected 1 package: tokencover(0.9.7)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at #hook (foundry.js:31843:11)
    at UserTargets.add (foundry.js:31818:15)
    at TokenPF2e.setTarget (foundry.js:60980:20)
    at Object._onTarget [as onDown] (foundry.js:1838:13)
    at KeyboardManager._executeKeybind (foundry.js:2462:66)
    at KeyboardManager._processKeyboardContext (foundry.js:2503:33)
    at KeyboardManager._handleKeyboardEvent (foundry.js:2561:10)
    at foundry.js:2175:54Caused by: TypeError: Cannot assign to read only property '_id' of object '#<EffectPF2e>'
[Detected 1 package: tokencover(0.9.7)]
    at CoverPF2E._addToTokenLocally (UniqueItemEffect.js:75:27)
    at CoverPF2E.addToTokenLocally (AbstractUniqueEffect.js:377:16)
    at TokenCover._replaceCover (TokenCover.js:443:49)
    at TokenCover.updateCover (TokenCover.js:406:22)
    at TokenCover.targetStatusChanged (TokenCover.js:382:40)
    at Object.targetToken [as fn] (Token.js:286:21)
    at #call (foundry.js:632:20)
    at Hooks.callAll (foundry.js:589:17)
    at #hook (foundry.js:31843:11)
    at UserTargets.add (foundry.js:31818:15)
    at TokenPF2e.setTarget (foundry.js:60980:20)
    at Object._onTarget [as onDown] (foundry.js:1838:13)
    at KeyboardManager._executeKeybind (foundry.js:2462:66)
    at KeyboardManager._processKeyboardContext (foundry.js:2503:33)
    at KeyboardManager._handleKeyboardEvent (foundry.js:2561:10)
    at foundry.js:2175:54
    
Thanks !

**Comment by robertdecaire** [comment] 2024-11-13 15:45
Same problem here. I'm getting the following errors:

```
foundry.js:655 Error: Error thrown in hooked function 'refreshToken' for hook 'refreshToken'. Cannot assign to read only property '_id' of object '#<EffectPF2e>'
[Detected 1 package: tokencover(0.9.7)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at TokenPF2e.applyRenderFlags (foundry.js:26658:11)
    at #applyRenderFlags (foundry.js:26282:44)
    at mn.emit (TickerListener.ts:71:47)
    at Pt.update (Ticker.ts:427:37)
    at Pt._tick (Ticker.ts:129:22)
onError @ foundry.js:655
```
```
foundry.js:655 Error: Error thrown in hooked function 'destroyToken' for hook 'destroyToken'. Cannot assign to read only property '_id' of object '#<EffectPF2e>'
[Detected 1 package: tokencover(0.9.7)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at TokenPF2e.destroy (foundry.js:26692:11)
    at foundry.js:34385:9
    at Array.forEach (<anonymous>)
    at TokenLayerPF2e.clearPreviewContainer (foundry.js:34383:35)
    at #commitDragLeftDropUpdates (foundry.js:27559:16)
onError @ foundry.js:655
```
```
foundry.js:655 Error: Error thrown in hooked function 'controlToken' for hook 'controlToken'. Cannot assign to read only property '_id' of object '#<EffectPF2e>'
[Detected 1 package: tokencover(0.9.7)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at TokenPF2e.control (foundry.js:26890:11)
    at TokenPF2e._onClickLeft (foundry.js:27321:35)
    at TokenPF2e._onClickLeft (foundry.js:61459:11)
    at MouseInteractionManager.callback (foundry.js:30834:17)
    at #handleClickLeft (foundry.js:31035:15)
    at #handleLeftDown (foundry.js:31017:38)
    at #handlePointerDown (foundry.js:30981:58)
    at vh.notifyListeners (EventBoundary.ts:1454:26)
    at vh.notifyTarget (EventBoundary.ts:662:18)
    at vh.propagate (EventBoundary.ts:299:14)
    at vh.dispatchEvent (EventBoundary.ts:210:14)
    at vh.mapPointerDown (EventBoundary.ts:683:14)
    at vh.mapEvent (EventBoundary.ts:231:28)
    at ra.onPointerDown (EventSystem.ts:373:31)
onError @ foundry.js:655
```
```
foundry.js:655 Error: Error thrown in hooked function 'targetToken' for hook 'targetToken'. Cannot assign to read only property '_id' of object '#<EffectPF2e>'
[Detected 1 package: tokencover(0.9.7)]
    at Hooks.onError (foundry.js:654:24)
    at 🎁Hooks.onError#0 (libWrapper-wrapper.js:188:54)
    at #call (foundry.js:636:36)
    at Hooks.callAll (foundry.js:589:17)
    at #hook (foundry.js:31843:11)
    at UserTargets.add (foundry.js:31818:15)
    at TokenPF2e.setTarget (foundry.js:60980:20)
    at TokenPF2e._onClickLeft (foundry.js:61457:19)
    at MouseInteractionManager.callback (foundry.js:30834:17)
    at #handleClickLeft (foundry.js:31035:15)
    at #handleLeftDown (foundry.js:31017:38)
    at #handlePointerDown (foundry.js:30981:58)
    at vh.notifyListeners (EventBoundary.ts:1454:26)
    at vh.notifyTarget (EventBoundary.ts:662:18)
    at vh.propagate (EventBoundary.ts:299:14)
    at vh.dispatchEvent (EventBoundary.ts:210:14)
    at vh.mapPointerDown (EventBoundary.ts:683:14)
    at vh.mapEvent (EventBoundary.ts:231:28)
    at ra.onPointerDown (EventSystem.ts:373:31)
onError @ foundry.js:655
```
Complete log attached:
[localhost-1731512542215.log](https://github.com/user-attachments/files/17735204/localhost-1731512542215.log)

**Comment by weepingminotaur** [comment] 2024-11-22 17:01
Same problem here.

**Comment by Asherlock** [comment] 2024-11-26 16:46
Seeing a similar issue here. 
![image](https://github.com/user-attachments/assets/44994dc6-eca9-4c8f-a82c-0840f109ebc5)

![image](https://github.com/user-attachments/assets/7aa09c9e-bb6f-423c-b1b9-f7518026241e)

**Closed** 2024-12-20 18:26 UTC
